// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_9oJYXbvOE6_RQNEQLD0yxwAFaJKZFew',
    appId: '1:589032959855:web:ba23ff9a908339a1ae429a',
    messagingSenderId: '589032959855',
    projectId: 'ella-med-app',
    authDomain: 'ella-med-app.firebaseapp.com',
    storageBucket: 'ella-med-app.appspot.com',
    measurementId: 'G-CH65XEXYZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeNzZEaSpYkB6Paljj2UV650-gfr8EpFA',
    appId: '1:589032959855:android:a7d445cd42613d8fae429a',
    messagingSenderId: '589032959855',
    projectId: 'ella-med-app',
    storageBucket: 'ella-med-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYpCtx0uyBTKGmCLrRcchgWdByfqfhGnc',
    appId: '1:589032959855:ios:c0e285c8ba060ec8ae429a',
    messagingSenderId: '589032959855',
    projectId: 'ella-med-app',
    storageBucket: 'ella-med-app.appspot.com',
    iosBundleId: 'com.example.ellaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYpCtx0uyBTKGmCLrRcchgWdByfqfhGnc',
    appId: '1:589032959855:ios:781082a13281725fae429a',
    messagingSenderId: '589032959855',
    projectId: 'ella-med-app',
    storageBucket: 'ella-med-app.appspot.com',
    iosBundleId: 'com.example.ellaApp.RunnerTests',
  );
}
